"""Localized short strings of the generated Workshop Guide (SPEC D10, designs[1]).

``STRINGS[lang][key]`` for ``lang`` in ``en`` and ``zh-CN``; both languages carry
exactly the same keys (a test pins it). Long-form text lives in ``templates/guide/*.md``; this module
holds what several places reuse: provenance tags, banners, table headers, kind / category labels, the
THELMA tag legend (the tags the template's evaluators print, quoted verbatim in both languages), the
diagnosis patterns of ``thelma_eval/evaluators/thelma/interplay.py``, the RCOF codes of
``mtg_eval/shared/models.py``, the 13 stability verdicts, retry messages, troubleshooting rows and the
instructor's run sheet and facilitation notes.

Nothing here names the template's own domain: no template identifier, no residue word (a static test
scans this file and the templates). Placeholders use ``str.format`` names in braces.
"""

from __future__ import annotations

#: The six interplay patterns (pattern, meaning, component) exactly as interplay.py prints them.
DIAGNOSIS_PATTERNS: tuple[tuple[str, str], ...] = (
    ("SD↓ RP↑", "Prompt or Generator"),
    ("SQC↓ RQC↓", "Retriever or Source text"),
    ("SP↓ SQC↑", "Retriever"),
    ("RQC↓ SQC↑", "Prompt or Generator"),
    ("RP↓ SP1↑", "Prompt or Source chunking"),
    ("SQC↓ RQC↑ GR↓", "Prompt"),
)

#: RCOF codes as mtg_eval/shared/models.py names them.
RCOF: tuple[tuple[str, str], ...] = (
    ("E1", "Language Understanding Failure"),
    ("E2", "Refusal to Answer"),
    ("E3", "Incorrect Retrieval"),
    ("E4", "Retrieval Failure"),
    ("E5", "System Error"),
    ("E6", "Incorrect Routing"),
    ("E7", "Out-of-Domain Query"),
)

#: THELMA printed tags (the explanation line of thelma_eval/lambda_function.py), metric key order.
THELMA_TAGS: tuple[tuple[str, str], ...] = (
    ("GR", "GR(接地/防幻觉)"),
    ("SP1", "SP1(块级检索精度)"),
    ("SP2", "SP2(事实级检索精度)"),
    ("SQC", "SQC(源覆盖)"),
    ("RP", "RP(响应精度)"),
    ("RQC", "RQC(响应覆盖)"),
    ("SD", "SD(去重)"),
)

#: interplay.py LOW / HIGH and the 13 verdict bounds on the standard deviation.
INTERPLAY_LOW, INTERPLAY_HIGH = 0.5, 0.7
STABILITY_STABLE, STABILITY_MODERATE = 0.03, 0.08
#: THELMA GR and Mind the Goal GSR pass lines of the pinned evaluators.
MTG_PASS_PERCENT = 80

STRINGS: dict[str, dict[str, object]] = {
    "en": {
        # -- provenance ---------------------------------------------------------------------------
        "tag.customer_confirmed": "[Customer-confirmed]",
        "tag.sa_synthetic": "[Synthetic teaching setting]",
        "tag.ai_draft": "[Draft — not for class]",
        "tag.pending": "[Draft — not for class]",
        "banner.reference": "Everything in this scenario is synthetic teaching material; none of it is a real organization's policy.",
        "banner.customer": (
            "This scenario is built from materials of {name}. Only statements tagged [Customer-confirmed] describe "
            "{name}'s actual rules. Items tagged [Synthetic teaching setting] were created for this class (some derived "
            "from {name} materials) and must not be quoted as {name} policy."
        ),
        "banner.classification": "Contains {name} {classification} material — do not share outside this class.",
        "classification.internal": "internal",
        "classification.confidential": "confidential",
        "the_customer": "the customer",
        "banner.draft": (
            "> [!WARNING]\n> **DRAFT PREVIEW** — rendered from an unreviewed scenario. Items tagged [Draft — not for class] "
            "have not been reviewed; a formal build refuses them. Do not hand this preview to participants."
        ),
        "banner.instructor": (
            "> [!CAUTION]\n> **INSTRUCTOR ONLY** — contains holdout cases and expected answers. Never copy it into the "
            "release, slides or chat."
        ),
        "none": "none",
        "none_facts": "_none — no statement in this scenario is customer-confirmed._",
        "none_synthetic": "_none_",
        "yes": "yes",
        "no": "no",
        "dash": "—",
        "colon": ": ",
        "category.normal": "normal",
        "category.boundary": "boundary",
        "category.prohibited": "prohibited",
        "criticality.blocking": "blocking",
        "criticality.advisory": "advisory",
        # -- teaching kinds -----------------------------------------------------------------------
        "kind.memory": "Memory (first conversation)",
        "kind.prompt_fixable": "Prompt-fixable",
        "kind.retrieval_gap.buried": "Retrieval gap (buried answer)",
        "kind.retrieval_gap.absent": "Retrieval gap (answer not in the knowledge base)",
        "kind.noise_grounding": "Noisy sources",
        "kind.tool_use": "Tool use",
        "kind.refusal": "Refusal",
        "kind.escalation": "Hand-off",
        "scored.probe": "L1 + THELMA + Mind the Goal",
        "scored.other": "L1 + Mind the Goal",
        # -- scenario table -----------------------------------------------------------------------
        "row.audience": "Who asks",
        "row.purpose": "What it does",
        "row.scope": "In scope",
        "row.out_of_scope": "Out of scope",
        "row.handoff": "Hands off to a person when",
        "row.prohibited": "Must never",
        "h.roles": ("Role", "Description", "Permissions"),
        "h.facts": ("Statement", "Criticality", "Tag"),
        "assets": (
            "In this scenario: {docs} knowledge document(s) ({doc_tags}; {noise} with deliberate teaching noise); "
            "{tools} tool(s) — 1 knowledge-base retrieval tool and {mocks} simulated tool(s) that return deterministic "
            "synthetic data; {cases} practice question(s) ({case_tags})."
        ),
        "count_tag": "{n} {tag}",
        # -- names / architecture ------------------------------------------------------------------
        "h.names": ("Resource", "Name"),
        "name.agent": "Agent (Harness)",
        "name.memory": "Memory",
        "name.gateway": "Gateway",
        "name.target": "Gateway target (trace tool prefix)",
        "name.lambda": "Tools Lambda",
        "name.retrieval": "Knowledge-base retrieval tool",
        "name.kb": "Knowledge Base (S3 Vectors)",
        "name.kb_prefix": "Knowledge-base S3 prefix",
        "name.ssm": "SSM parameters",
        "name.evaluators": "Evaluators",
        "name.skills": "Skills",
        "name.runs": "Run records (on the Workshop EC2)",
        "diagram.user": "User",
        "diagram.harness": "Harness",
        "diagram.gateway": "Gateway",
        "diagram.lambda": "Lambda",
        "diagram.kb": "Knowledge Base",
        "diagram.mocks": "Simulated tools",
        "diagram.memory": "Memory",
        "diagram.skills": "Skills",
        "no_skills": "no skills",
        # -- documents / tools / practice ----------------------------------------------------------
        "h.documents": ("Title", "File", "Source", "Teaching noise"),
        "h.tools": ("Tool", "What it does", "Kind", "Source"),
        "tool.retrieval": "Knowledge-base retrieval",
        "tool.mock": "Simulated system (deterministic synthetic data)",
        "h.practice": ("#", "Question", "Asked", "Category", "Persona", "Scored by", "Source"),
        "skills.some": "Copies the {n} SKILL.md file(s) ({names}) from `pack/skills/` and uploads them to the S3 data bucket under `skills/`.",
        "skills.none": "This scenario has no Skills; the script only verifies the data bucket.",
        # -- execution order -----------------------------------------------------------------------
        "h.execution": ("#", "Script", "Phase", "~Time", "What it creates / does"),
        "exec.setup": "Verify CLIs, create `~/workshop` dirs{skills}",
        "exec.infra": "**Required.** CFN stack `workshop-infra`: VPC + subnets + NAT + SG, S3 data bucket + Access Point, EC2 (already present in a prepared environment: the script prints its outputs)",
        "exec.kb": "Knowledge Base `{kb}` (**S3 Vectors**) + the scenario's {docs} documents + ingestion; writes the KB ID to SSM",
        "exec.gateway": "Deploy the tools **Lambda** `{fn}` + IAM role, then create the **Gateway** `{gw}` with {tools} tools",
        "exec.skills": "Upload the scenario's Skills to S3{skills}",
        "exec.agent": "Create the **Harness** `{agent}` and Memory `{memory}`, attach the Gateway + Skills, deploy (single-pass)",
        "exec.memory": "Configure Memory **retrieval** on the Harness (waits for Runtime READY)",
        "exec.conversation": "Run the first conversation as `{actor}` (generates a trace)",
        "exec.eval_env": "Install `uv` + enable CloudWatch **Transaction Search**",
        "exec.rerun": "Regenerate a trace **after** Transaction Search is on",
        "exec.evaluators": "Register + deploy the THELMA & Mind the Goal evaluators",
        "exec.baseline": "Ask the {total} practice questions, wait for the {n} retrieval traces, then evaluate (THELMA, Mind the Goal, L1)",
        "exec.optimize": "Install the optimized prompt on the deployed Harness (about 30 s), re-ask the {total} questions + re-evaluate the {n} retrieval traces",
        "exec.cost": "_Optional._ Latency + tokens + cost of the most recent {n} retrieval traces from `aws/spans` (no new resources)",
        "exec.models": "_Optional lab A._ Switch the deployed Harness to another model in place (about 30 s, no redeploy), re-ask the {total} questions + re-evaluate, compare, then switch back",
        "exec.stability": "_Optional lab B._ Score the same trace {runs} times to check judge repeatability",
        "exec.cleanup": "Tear everything down, including the Customizer add-on stack (reverse dependency order; idempotent)",
        "exec.again": "*(again)*",
        "exec.required_time": "~5 min",
        "timing_footnote": (
            "\\* Timings are the template's, measured with 3 questions. This scenario asks {total} practice questions, "
            "judges every one with Mind the Goal and runs L1 checks (up to {l1_wait} s of span polling), so 09, 10 and 12 "
            "take longer."
        ),
        # -- step 8 / notes --------------------------------------------------------------------------
        "scenario_note": "> **Scenario note:** {text}",
        # -- reading the output ------------------------------------------------------------------------
        "h.legend": ("Printed tag", "Metric", "Question it answers", "A low score means"),
        "legend": (
            ("Groundedness", "Is every sentence backed by a retrieved source? Pass ≥ {gr}.", "the answer says things the sources do not (hallucination or outside knowledge)"),
            ("Source Precision (chunk)", "Are the retrieved chunks relevant as a whole?", "retrieval returned off-topic chunks"),
            ("Source Precision (fact)", "Of the facts inside those chunks, how many are relevant?", "the chunks carry mostly noise; near 0 means retrieval failed"),
            ("Source Query Coverage", "Do the sources cover the question?", "the answer is not in what was retrieved"),
            ("Response Precision", "Is the answer on-topic?", "the answer pads with unrelated content"),
            ("Response Query Coverage", "Is the question fully answered?", "parts of the question are left open"),
            ("Self-Distinctness", "No internal repetition?", "the answer repeats itself"),
        ),
        "h.diagnosis": ("Printed pattern", "What it means", "Component to fix"),
        "diagnosis": (
            "Lengthier responses with relevant but repetitive information, low user readability",
            "Inaccurate retrieval OR missing information in source corpora",
            "All query components addressed, but some retrieved sources only loosely relevant",
            "Information required to answer is present in source but not used in response",
            "Response contains extraneous information but majority of retrieved sources are essential",
            "Generator responding to queries not addressed in source, causing ungroundedness",
        ),
        "diagnosis.extra": (
            ("SP1 high · SP2 low", "The chunk looks on topic but most facts in it are noise", "Source documents (clean the knowledge base)"),
            ("SP2 ≈ 0", "Retrieval failed: the relevant fact was not retrieved", "Retrieval — a prompt change cannot help"),
        ),
        "diagnosis.levels": "LOW < {low}, HIGH ≥ {high}. `诊断: 无` means no pattern matched.",
        "h.rcof": ("Code", "Root cause of failure"),
        "mtg.reading": (
            "`value` = GSR ÷ 100; a session passes at GSR ≥ {gsr}%. `失败归因: E2:1` counts failed goals by RCOF code; "
            "`无失败` means none failed."
        ),
        "h.l1": ("Status", "Meaning"),
        "l1.statuses": (
            ("PASS", "every declared check of the question passed"),
            ("FAIL", "a check failed: the detail column names it (for example `mustMention fail: …`)"),
            ("DEFER", "L1 cannot decide (a refusal or hand-off without a marker, a negated forbidden phrase); Mind the Goal decides"),
            ("UNVERIFIED", "the evidence was not there yet (no response found, tool spans not indexed)"),
            ("ERROR", "the invoke itself failed"),
        ),
        "l1.compare": (
            "In 10 the table ends with `Against baseline-<epoch>:` and the flips `fixed`, `regressed` and `still-failing`; "
            "a still-failing question with SP2≈0 in both runs is marked `fix retrieval / the knowledge base, not the prompt`."
        ),
        "h.messages": ("Message", "What it means"),
        "messages": (
            ("`(spans not indexed yet, retry in {pause}s n/{attempts})`", "the trace is not visible to the evaluator yet; the script retries on its own"),
            ("`(span evidence incomplete, retry in {pause}s n/{attempts})`", "the evaluator ran but saw an incomplete trace; the script retries on its own"),
            ("`已索引含检索 trace: x/y`", "the index wait: x of the y expected retrieval traces are ready"),
            ("`超时（仅 x/y 条就绪）`", "the wait timed out: a question expected to retrieve did not call the retrieval tool (read its answer above)"),
            ("`ERROR: evaluator did not return a usable score` / `ERROR: no usable evaluation scores`", "the judge returned nothing usable; the script exits 1 — run it again"),
        ),
        "look.noise": "Traces that retrieve {docs}: SP1 high but SP2 low — the chunks look on topic but carry off-topic lines.",
        "look.gap": "{labels}: SP2 ≈ 0 or SQC low — retrieval did not find the answer.",
        "look.fixable": "{labels}: sources cover the question (SQC ≥ {sqc}) but GR is below {gr} — the baseline prompt lets the model elaborate beyond the sources.",
        # -- what you should see ----------------------------------------------------------------------
        "h.expect": ("Moment", "Question(s)", "What you should see", "Why"),
        "expect.memory.where": "Step 8 (`06`)",
        "expect.memory": "A generic answer, then the notice `{notice}` — the agent does not know this user yet. Step 10 asks the same question as the same actor.",
        "expect.prompt_fixable": "09: GR below {gr} (Fail) although the sources cover the question (SQC ≥ {sqc}). After 10: GR rises by more than max(noise band, {bar}) — the prompt fix works.",
        "expect.retrieval_gap.buried": "09 and 10: retrieval fails (SP2 ≤ {sp2} or SQC < {sqc}) and the answer **stays Fail** after 10 — a prompt change cannot fix it; fix retrieval / the knowledge base.",
        "expect.retrieval_gap.buried.advisory": "09 and 10: retrieval often fails (SP2 ≤ {sp2} or SQC < {sqc}), but a rephrased retrieval may find the buried answer, so it can pass after 10. Advisory: the class contrast rests on the gap whose answer is not in the knowledge base.",
        "expect.retrieval_gap.absent": "09 and 10: **retrieval finds nothing** relevant (SP2 ≤ {sp2} or SQC < {sqc}). After 10 **the optimized agent admits it and hands off** (L1 checks the hand-off); GR may even pass — the prompt fixed honesty, not coverage.",
        "expect.tool_use.control": "L1 `requiredTools` / `forbiddenTools` pass: the answer comes from the Gateway tool, not the knowledge base.",
        "expect.tool_use.contrast": "09: L1 tool checks fail. After 10: they pass — the answer comes from the Gateway tool.",
        "expect.refusal.control": "The agent refuses (L1 `shouldRefuse` passes; Mind the Goal counts a refusal the scenario requires as success).",
        "expect.refusal.contrast": "09: the baseline does not refuse (L1 fails). After 10: it refuses (L1 `shouldRefuse` passes).",
        "expect.escalation.control": "The agent hands off to the right team (L1 `shouldEscalate` passes).",
        "expect.escalation.contrast": "09: the baseline does not hand off (L1 fails). After 10: it hands off (L1 `shouldEscalate` passes).",
        "expect.noise_grounding": "Traces that retrieve these documents show SP1 high but SP2 low (noisy chunks). Advisory: it never decides the contrast.",
        "expect.documents": "Documents: {titles}",
        "expect.noise_band": (
            "The noise band is how much THELMA moves on its own between identical runs; your facilitator measures it with "
            "`13-judge-stability.sh`. A change smaller than max(noise band, {bar}) is not an improvement."
        ),
        # -- step 13 -----------------------------------------------------------------------------------
        "contrast.intro": "Compare against the pre-optimization scores (the L1 table of 09 and 10 lists every practice question):",
        "contrast.fixable": "where retrieval is good ({labels}), grounding and precision improve — the prompt fix works;",
        "contrast.buried": "{labels} (SP2≈0, retrieval failure) **stays Fail** — a prompt change can't fix it;",
        "contrast.buried.advisory": "{labels} (a buried answer): retrieval often fails (SP2≈0), but a rephrased retrieval may find the answer and pass after 10 — advisory; the next item is the reliable contrast;",
        "contrast.absent": "{labels}: **retrieval finds nothing**, and the optimized agent **admits it and hands off** instead of inventing an answer — the prompt fixed honesty, not coverage.",
        "contrast.close": "That contrast **confirms the THELMA diagnosis**: it distinguishes \"fix the Prompt\" from \"fix retrieval\".",
        "contrast.undeclared": (
            "Compare against the pre-optimization scores: for questions where retrieval is good, grounding/precision "
            "improve; a question whose retrieval failed (SP2≈0) stays Fail — a prompt change can't fix it."
        ),
        "adlc.tip": "In this scenario: the prompt change should raise grounding for {fixable}, but it cannot fix {gaps}: {why}.",
        "adlc.tip.buried": "their retrieval fails (SP2≈0)",
        "adlc.tip.absent": "the knowledge base has no answer, so the optimized agent must admit it and hand off",
        "adlc.tip.mixed": "their retrieval fails or the knowledge base has no answer",
        "adlc.undeclared": (
            "The payoff is the contrast: a prompt change improves grounding where retrieval is good, but **can't** fix a "
            "question whose retrieval failed (`SP2≈0`)."
        ),
        "join.and": " and ",
        "join.list": ", ",
        # -- attribution ---------------------------------------------------------------------------------
        "attr.kb": "The knowledge base holds {docs} document(s) written for this scenario ({doc_tags}); {noise} carry deliberate teaching noise so THELMA can surface retrieval-quality problems.",
        "attr.customer": "Customer materials are used with the customer's approval.",
        "generated_by": "_Generated by Workshop Customizer {version} for scenario pack `{pack}` from template commit `{commit}`._",
        "supplement.heading": "Scenario notes",
        # -- instructor ------------------------------------------------------------------------------------
        "h.meta": ("Field", "Value"),
        "meta.pack": "Scenario pack",
        "meta.kind": "Pack kind",
        "meta.language": "Language",
        "meta.template": "Template commit",
        "meta.generator": "Generator version",
        "meta.scenario": "Scenario file sha256",
        "h.matrix": ("Items", "customer_confirmed", "sa_synthetic", "ai_draft", "pending"),
        "matrix.facts": "Facts",
        "matrix.tools": "Tools",
        "matrix.documents": "Documents",
        "matrix.golden": "Golden cases",
        "matrix.narrative": "Guide narrative",
        "waived": "Waived gate findings: {items}",
        "h.anchors": ("Category", "Confirmed golden cases with confirmed basis", "Status"),
        "anchor.ok": "OK",
        "anchor.missing": "MISSING",
        "anchors.note": "Informational: a customer-confirmed anchor per category is what a class-use customer scenario needs; reference packs are synthetic by design.",
        "classification.line": "Data classification: {value}.",
        "customer.line": "Customer: {name}; material approval: {approval}.",
        "classification.unset": "not declared (synthetic reference material)",
        "h.declarations": ("Declaration", "Value"),
        "decl.first": "First conversation (06)",
        "decl.probes": "Retrieval probes P (09 want = N = RECENT_N)",
        "decl.fixable": "Prompt-fixable",
        "decl.gaps": "Retrieval gaps",
        "decl.stability": "Stability case (asked last; 13 re-scores it)",
        "decl.order": "Eval order (09 / 10 / 12)",
        "decl.declared": "DECLARED",
        "decl.undeclared": "NOT DECLARED — the class cannot reliably demonstrate the contrast",
        "warnings.none": "No validator warnings.",
        "checklist": (
            "All 15 Guided Run steps passed on the release you teach (`{version}`), and the report status is complete.",
            "The baseline has {n} usable THELMA scores (one per retrieval probe).",
            "Prompt-fixable probes ({fixable}): GR gain > max(noise band, {bar}) with sampleCountsMatch = true.",
            "Retrieval gaps ({gaps}): SP2 ≤ {sp2} or SQC < {sqc} in both runs; {gap_outcome}.",
            "Tool-use, refusal and hand-off questions pass their L1 focus checks after 10.",
            "Judge stability recorded (13) and the noise band applied (≤ {band_max}).",
            "`run/rehearsal.json` says ready for class for this release.",
            "Only the customer-confirmed facts (table 2.1) are presented as the organization's rules.",
        ),
        "gap_outcome.buried": "buried gaps stay Fail after 10",
        "gap_outcome.absent": "for absent gaps the optimized answer admits the gap and hands off",
        "gap_outcome.mixed": "for absent gaps the optimized answer admits the gap and hands off; buried gaps ({buried}) are advisory: a rephrased retrieval may find their answer and pass after 10",
        "h.runsheet": ("Guide step", "Script", "Guided Run", "~Time", "Participants should see", "Facilitator note"),
        "run.not_guided": "not in the Guided Run",
        "run.separate": "separate destructive flow",
        "h.truth_facts": ("Id", "Statement", "Criticality", "Confirmed by", "Reference / source", "Class (origin)"),
        "h.truth_docs": ("Id", "Title", "File", "Provenance", "Teaching noise", "Teaching role"),
        "h.truth_tools": ("Tool", "Kind", "Provenance", "Behavior"),
        "tool.default": "default",
        "tool.when": "when",
        "tool.error": "error",
        "doc.role.noise": "noise_grounding",
        "doc.role.bait": "bait",
        "doc.role.answer": "answer to {cases}",
        "h.answer": ("Field", "Value"),
        "answer.question": "Question",
        "answer.asked": "Asked as",
        "answer.expected": "Expected",
        "answer.basis": "Basis",
        "answer.roles": "Teaching role",
        "answer.evaluated": "Evaluated by",
        "answer.persona": "persona `{persona}` (fresh runtime actor `{persona}-<RUN_TAG>-q{index}`), role `{role}`",
        "answer.declared_actor": "declared actor `{actor}`, role `{role}`",
        "answer.holdout_eval": "not executed (holdout)",
        "answer.stability": "stability case",
        "answer.probe": "retrieval probe",
        "holdout.use": (
            "Holdout cases are not executed by any script in this release, and no App route invokes them (the trust model "
            "allows only the two fixed SSM documents). Use them after the class run for discussion: ask one by hand in "
            "the Workshop environment (`npx agentcore invoke` from `~/workshop/{agent}`), then compare the answer with the "
            "expected values above. Never paste them into slides or chat while participants can see."
        ),
        "rehearsal.none": (
            "No rehearsal evidence is recorded for this build yet. After the Guided Run on this release, the App shows "
            "the rehearsal verdict here (the instructor guide view) and adds `rehearsal-evidence.md` to the instructor bundle."
        ),
        "fallback.generic": (
            "Class fallback: if this scenario's rehearsal is not ready, or its run breaks in class, teach the generic "
            "workshop (`hr-default`, the upstream-compatible reference pack) instead — but only in an environment prepared "
            "for it. The add-ons stack grants the Workshop EC2 its permissions for one pack namespace, so hr-default cannot "
            "run in this scenario's environment, and a rollback swaps release files only. Keep a separate environment with "
            "hr-default synced and rehearsed (its own rehearsal must say ready for class), or, before class, run "
            "`./99-cleanup.sh --scenario-only`, redeploy the add-ons with "
            "`tools/deploy_addons.py --scenario scenarios/hr-default/scenario.yaml` (this scenario then no longer runs "
            "there), sync hr-default and rehearse it."
        ),
        "rehearsal.bundle_title": "Rehearsal evidence — {version}",
        "rehearsal.verdict": "Verdict: **{verdict}**",
        "rehearsal.ready": "Ready for class: **{ready}**",
        "rehearsal.release": "Release: `{release}`",
        "rehearsal.generated": "Generated at: {at}",
        "rehearsal.reason": "Reason: {reason}",
        "rehearsal.blockers": "Readiness blockers: {blockers}",
        "rehearsal.report_complete": "Guided Run report complete: **{value}**",
        "rehearsal.guides_built": "Both guides built: **{value}**",
        "rehearsal.noise_band": "Judge noise band: {value}",
        "rehearsal.noise_source": "source {source}",
        "rehearsal.noise_verdict": "stability verdict {verdict}",
        "rehearsal.missing": "Missing evidence: {items}",
        "rehearsal.stale": "This evidence belongs to release `{release}`, not the release of this guide; rehearse again before class.",
        "h.rehearsal": ("Phenomenon", "Kind", "Verdict", "Evidence"),
        "rehearsal.remediation": "Remediation hints:",
        "rehearsal.empty": "The rehearsal record lists no phenomena.",
        "rehearsal.blocker": "{code} ({text})",
        "rehearsal.evidence_sep": "; ",
        "rehearsal.case": "{case}: {code}",
        "rehearsal.case_reason": "{case}: {code} — {reason}",
        "rehearsal.warnings": "Warnings:",
        "rehearsal.warning_refs": "{refs}: {text}",
        "rehearsal.code_reason": "{code} — {reason}",
        "rehearsal.list_sep": ", ",
        "rehearsal.noise_details": "{value} ({details})",
        "rehearsal.hint": "{action} ({because})",
        "rehearsal.sentence_end": "",
        "rehearsal.hint_where": "{where}: {text}",
        "rehearsal.hint_tagged": "**{severity}** {text}",
        "rehearsal.severity.blocking": "Blocking",
        "rehearsal.severity.advisory": "Advisory",
        "report.fields": (
            ("`report.teachingContrast.currentRun`", "reproduced / not_reproduced / insufficient_evidence for this one run; each phenomenon lists per-case codes"),
            ("`quality.delta.<evaluator>`", "baseline vs optimized mean; counts as a change only with sampleCountsMatch = true and |delta| > noise band"),
            ("`quality.regressions`", "evaluators whose mean dropped by more than the noise band"),
            ("`quality.comparisonWarnings`", "different numbers of usable scores: the mean difference is descriptive only"),
            ("`completion.missingEvidence`", "evidence a step did not deliver (per-case L1, per-case Mind the Goal, noise band)"),
            ("`scopeWarning`", "the report validates the Workshop run, not a production launch"),
            ("`run/rehearsal.json` `readyForClass`", "the only readiness decision (verdict ready ∧ report complete ∧ both guides built)"),
        ),
        "h.report": ("Report field", "How to read it"),
        "h.facilitation": ("Code in the report", "What happened", "What to say in class", "After class"),
        "facilitation": (
            ("PF_BASELINE_ALREADY_PASSES", "The baseline already grounded this probe (GR ≥ {gr}).", "The prompt defects did not bite on this question today; show a probe that did improve.", "Strengthen the baseline defect or the noise near the answer, rebuild, rehearse again."),
            ("PF_NO_GAIN", "GR moved less than max(noise band, {bar}).", "LLM judges fluctuate; read the trend and the diagnosis, not one number.", "Re-run 09/10 once in rehearsal; if it repeats, revisit the candidate prompt."),
            ("PF_RETRIEVAL_FAILED", "The sources did not cover the question (max SQC < {sqc}).", "This is a retrieval problem, not a prompt problem — the same lesson as the gap.", "Check the answer document and chunking; rebuild."),
            ("RG_RETRIEVAL_OK_BASELINE / RG_RETRIEVAL_OK_OPTIMIZED", "Retrieval found the gap question's answer (SP2 > {sp2} and SQC ≥ {sqc_gap}).", "Today retrieval happened to work; explain what SP2≈0 would have shown.", "Remove the answer from the knowledge base (absent) or bury it deeper (buried); rebuild."),
            ("RG_OPTIMIZED_RESOLVED", "A buried gap was labelled Pass after 10.", "Point at SP2: retrieval still failed. Read the optimized answer: if it states the fact, a rephrased search (or the model's own knowledge) supplied it; if it says it found nothing and hands off, the judge passed a grounded non-answer.", "Teach the gap on the absent question; a buried gap is unreliable (if the pack has no absent gap, add one)."),
            ("JUDGE_TOO_NOISY / NOISE_BAND_MISSING", "The noise band is above {band_max} or was never measured.", "Do not claim an improvement from THELMA numbers today.", "Run 13, calibrate evaluation.noiseBand, rebuild."),
            ("L1_UNRESOLVED / L1_MISSING", "L1 deferred and Mind the Goal gave no verdict, or L1 did not run.", "Read the answer aloud and judge it against the scenario rules in §1 of the student guide.", "Add escalation or refusal markers (evaluation.l1) so L1 can decide; rebuild."),
            ("L1_OPTIMIZED_FAILS", "The optimized agent failed a tool, refusal or hand-off check.", "A regression: the evaluator, not intuition, decides what ships.", "Fix the candidate prompt or the case expectations; rebuild."),
        ),
        "h.troubleshoot": ("Symptom", "Fix"),
        "troubleshooting": (
            ("`Stack 'workshop-infra' has no DataBucketName/SkillsBucketName output`", "Run step 2 (`00-deploy-infra.sh`) first."),
            ("`Gateway ARN not found in SSM`", "Run step 4 (`02-create-gateway.sh`)."),
            ("`04-deploy.sh` finds no `SkillsFilesAccessPointArn`", "The `workshop-customizer-addons` stack is missing: the environment is not prepared; deploy it from the App."),
            ("`05-setup-memory.sh`: requested release is not active", "Apply this release from the App (sync) so `~/workshop/current` points at it."),
            ("`Model access is denied` / `aws-marketplace:Subscribe`", "Enable model access, or set `WORKSHOP_MODEL_ID` in `00-config.sh` to a model the account can use."),
            ("`uv` is not found (08 cannot package the evaluators)", "`export PATH=\"$HOME/.local/bin:$PATH\"` (step 9)."),
            ("09 retry or `no usable evaluation scores`", "Run the same command again; the judge or the span index lagged."),
            ("09 index wait times out", "A question expected to retrieve did not; read its answer and the L1 table."),
            ("`Set verified PRICE_IN and PRICE_OUT`", "Export `PRICE_IN` / `PRICE_OUT` ($ per 1M tokens) for that model and region."),
            ("`Model produced invalid sequence as part of ToolUse`", "The comparison model (e.g. Nova Micro) cannot run this agent topology; pick another model."),
            ("09: a baseline answer ends with `Model stopped generating due to maximum token limit`", "A long answer ran to the 8192-token `--max-tokens` limit. The partial answer before the line is still scored (THELMA, Mind the Goal; L1 checks the partial answer, so a mustMention fail may come from the cut). Once on a baseline answer is expected when the baseline asks for extra advice; on several questions or on the optimized run, look at the prompt's length rules."),
            ("13 prints `数据不足`", "Fewer than two usable scores; run it again once traces are indexed."),
            ("99 exits 75 (`Cleanup pending`)", "AgentCore ENIs can take up to 8 hours to release; re-run the same command later."),
        ),
        "experiments.fix": (
            "Fix retrieval (discussion only; it needs a rebuilt release, never an in-class edit): clean the noisy "
            "documents or split the answer passage of a buried gap, or add the missing procedure for an absent gap; "
            "rebuild and rehearse again — the gap question should then be answered from the knowledge base."
        ),
        "observations.none": "No lab observations.",
        "supplement.none": "No facilitator supplement.",
        "design_rationale": "Design rationale:",
        "prompt.diff": "Baseline → optimization candidate (`pack/prompts/baseline.md` → `pack/prompts/optimization-candidate.md`):",
        "defects.intro": "Baseline defects the candidate fixes:",
        "h.defects": ("Defect", "What the baseline lacks", "The candidate's fix"),
        "memory.check": "Advisory memory check: the 06 answer must not mention {terms} (the user's own data).",
        "gap.terms": "Absent terms (must not be in the knowledge base): {terms}. Bait terms (in noise documents): {bait}.",
        "gap.bait": "Bait terms (in noise documents): {bait}.",
        "gap.docs": "Documents: answer {answer}; bait {bait}.",
        "l1.kind_note": "Design: {design}. Focus checks: {checks}.",
        # -- noise / experiments / run sheet (added) ------------------------------------------------
        "noise.lead": "To make the evaluation meaningful, the knowledge base is seeded with **deliberate teaching noise** — so the THELMA scores surface real retrieval-quality problems instead of a clean toy result:",
        "noise.none": "This scenario's knowledge base carries no deliberate teaching noise.",
        "noise.docs": "{n} of these documents carry deliberate teaching noise (off-topic passages), so retrieval-quality problems show up in THELMA.",
        "experiments.heading": "Scenario experiments",
        "run.see.setup": "account id and region; the Skill directories created",
        "run.see.infra": "the `workshop-infra` outputs (the stack already exists)",
        "run.see.knowledge-base": "KB `{kb}` details; {docs} documents ingested",
        "run.see.gateway": "Lambda `{fn}` and Gateway `{gw}`; the ARN written to SSM",
        "run.see.skills": "{skills} SKILL.md file(s) uploaded",
        "run.see.agent": "Harness `{agent}` deployed in VPC mode",
        "run.see.memory": "Runtime READY; Memory retrieval configured",
        "run.see.conversation": "the topic line, a generic answer, the memory notice",
        "run.see.eval-env": "`uv` installed; Transaction Search enabled",
        "run.see.conversation-rerun": "the same question as `{actor}`",
        "run.see.evaluators": "`{thelma}` and `{mtg}` registered; the judge model printed",
        "run.see.baseline": "{total} questions, {n} retrieval traces scored, Mind the Goal per question, the L1 table",
        "run.see.optimize": "the same {total} questions re-asked; L1 flips against the baseline; the closing reading",
        "run.see.cost-latency": "latency, tokens and cost of {recent} traces",
        "run.see.models": "comparison scores; the baseline model restored",
        "run.see.judge-stability": "{runs} scores of one trace, mean / std / spread and a verdict",
        "run.see.cleanup": "resources deleted, or `Cleanup pending` and exit status 75",
        "run.note.setup": "",
        "run.note.infra": "In the prepared environment the stack exists; the script only prints its outputs.",
        "run.note.knowledge-base": "Objects of an earlier pack under the KB prefix are pruned before ingestion.",
        "run.note.gateway": "",
        "run.note.skills": "",
        "run.note.agent": "Needs the `workshop-customizer-addons` stack (`SkillsFilesAccessPointArn`).",
        "run.note.memory": "Needs this release to be the active release on the host; the Guided Run refuses any other release.",
        "run.note.conversation": "The Guided Run runs 06 once, before 07; guide step 10 is a participant step only.",
        "run.note.eval-env": "",
        "run.note.conversation-rerun": "Participants only: Transaction Search captures spans created after step 9.",
        "run.note.evaluators": "Mind the Goal judges with the scenario policy (scope, hand-offs, prohibitions).",
        "run.note.baseline": "Mind the Goal failures are fatal only under the guided runner (`WORKSHOP_NONINTERACTIVE=1`).",
        "run.note.optimize": "Compare the closing reading with §3.2.",
        "run.note.cost-latency": "",
        "run.note.models": "The guided 12 is non-interactive and uses the target's comparison model.",
        "run.note.judge-stability": "Turn the spread into `evaluation.noiseBand` (App: calibrate) before class.",
        "run.note.cleanup": ("Never automatic and not part of the Guided Run. `--scenario-only` keeps `workshop-infra` "
                             "and the add-ons (re-sync a changed pack before class)."),
    },
    "zh-CN": {
        "tag.customer_confirmed": "［客户已确认］",
        "tag.sa_synthetic": "［合成教学设定］",
        "tag.ai_draft": "［草稿，不可用于课堂］",
        "tag.pending": "［草稿，不可用于课堂］",
        "banner.reference": "本场景的全部内容都是合成的教学材料，不代表任何真实组织的制度。",
        "banner.customer": (
            "本场景基于 {name} 的材料构建。只有标注［客户已确认］的陈述描述 {name} 的真实规则。标注［合成教学设定］的内容是"
            "为本课程编写的（部分源自 {name} 的材料），不得当作 {name} 的制度引用。"
        ),
        "banner.classification": "包含 {name} 的{classification}材料——不要在本课程之外分享。",
        "classification.internal": "内部",
        "classification.confidential": "机密",
        "the_customer": "客户",
        "banner.draft": (
            "> [!WARNING]\n> **草稿预览**——由未审核的场景渲染。标注［草稿，不可用于课堂］的内容尚未审核，正式构建会拒绝它们。"
            "不要把这份预览发给学员。"
        ),
        "banner.instructor": (
            "> [!CAUTION]\n> **仅限讲师**——包含留出集（holdout）问题和期望答案。绝不能复制到 release、幻灯片或聊天中。"
        ),
        "none": "无",
        "none_facts": "_无——本场景没有任何陈述经过客户确认。_",
        "none_synthetic": "_无_",
        "yes": "是",
        "no": "否",
        "dash": "—",
        "colon": "：",
        "category.normal": "常规",
        "category.boundary": "边界",
        "category.prohibited": "禁止",
        "criticality.blocking": "阻断",
        "criticality.advisory": "参考",
        "kind.memory": "Memory（第一次对话）",
        "kind.prompt_fixable": "改提示词可修",
        "kind.retrieval_gap.buried": "检索缺口（答案被埋没）",
        "kind.retrieval_gap.absent": "检索缺口（知识库里没有答案）",
        "kind.noise_grounding": "带噪声的来源",
        "kind.tool_use": "工具调用",
        "kind.refusal": "拒绝",
        "kind.escalation": "转交",
        "scored.probe": "L1 + THELMA + Mind the Goal",
        "scored.other": "L1 + Mind the Goal",
        "row.audience": "谁在提问",
        "row.purpose": "它做什么",
        "row.scope": "范围内",
        "row.out_of_scope": "范围外",
        "row.handoff": "何时转交给人工",
        "row.prohibited": "绝不能做",
        "h.roles": ("角色", "说明", "权限"),
        "h.facts": ("陈述", "重要性", "标注"),
        "assets": (
            "本场景：{docs} 份知识库文档（{doc_tags}；其中 {noise} 份带有刻意的教学噪声）；{tools} 个工具——1 个知识库检索工具和 "
            "{mocks} 个返回确定性合成数据的模拟工具；{cases} 个 practice 问题（{case_tags}）。"
        ),
        "count_tag": "{n} 项{tag}",
        "h.names": ("资源", "名称"),
        "name.agent": "Agent（Harness）",
        "name.memory": "Memory",
        "name.gateway": "Gateway",
        "name.target": "Gateway target（trace 中的工具前缀）",
        "name.lambda": "工具 Lambda",
        "name.retrieval": "知识库检索工具",
        "name.kb": "知识库（S3 Vectors）",
        "name.kb_prefix": "知识库 S3 前缀",
        "name.ssm": "SSM 参数",
        "name.evaluators": "评估器",
        "name.skills": "Skills",
        "name.runs": "运行记录（在 Workshop EC2 上）",
        "diagram.user": "用户",
        "diagram.harness": "Harness",
        "diagram.gateway": "Gateway",
        "diagram.lambda": "Lambda",
        "diagram.kb": "知识库",
        "diagram.mocks": "模拟工具",
        "diagram.memory": "Memory",
        "diagram.skills": "Skills",
        "no_skills": "无 Skills",
        "h.documents": ("标题", "文件", "来源", "教学噪声"),
        "h.tools": ("工具", "作用", "类型", "来源"),
        "tool.retrieval": "知识库检索",
        "tool.mock": "模拟系统（确定性的合成数据）",
        "h.practice": ("#", "问题", "提问内容", "类别", "身份", "评分方", "来源"),
        "skills.some": "从 `pack/skills/` 复制 {n} 个 SKILL.md 文件（{names}），并上传到 S3 数据桶的 `skills/` 下。",
        "skills.none": "本场景没有 Skills；脚本只校验数据桶。",
        "h.execution": ("#", "脚本", "阶段", "约耗时", "创建/做什么"),
        "exec.setup": "校验 CLI，创建 `~/workshop` 目录{skills}",
        "exec.infra": "**必须。** CFN 栈 `workshop-infra`：VPC + 子网 + NAT + SG，S3 数据桶 + Access Point，EC2（准备好的环境里已存在：脚本只打印输出）",
        "exec.kb": "知识库 `{kb}`（**S3 Vectors**）+ 本场景的 {docs} 份文档 + 入库；把 KB ID 写入 SSM",
        "exec.gateway": "部署工具 **Lambda** `{fn}` + IAM 角色，再创建带 {tools} 个工具的 **Gateway** `{gw}`",
        "exec.skills": "把本场景的 Skills 上传到 S3{skills}",
        "exec.agent": "创建 **Harness** `{agent}` 和 Memory `{memory}`，挂上 Gateway + Skills，部署（一次成型）",
        "exec.memory": "在 Harness 上配置 Memory **检索**（会等 Runtime READY）",
        "exec.conversation": "以 `{actor}` 身份跑第一次对话（生成一条 trace）",
        "exec.eval_env": "安装 `uv` + 开启 CloudWatch **Transaction Search**",
        "exec.rerun": "在 Transaction Search 开启**之后**重新生成一条 trace",
        "exec.evaluators": "注册 + 部署 THELMA 和 Mind the Goal 评估器",
        "exec.baseline": "问 {total} 个 practice 问题，等 {n} 条检索 trace 就绪，再评估（THELMA、Mind the Goal、L1）",
        "exec.optimize": "在已部署的 Harness 上换上优化后的提示词（约 30 秒），重问 {total} 个问题 + 重新评估 {n} 条检索 trace",
        "exec.cost": "_可选。_ 从 `aws/spans` 读出最近 {n} 条检索 trace 的延迟 + token + 成本（不新建资源）",
        "exec.models": "_可选实验 A。_ 在已部署的 Harness 上就地换模型（约 30 秒，不重新部署）、重问 {total} 个问题 + 重新评估、对比，再切回",
        "exec.stability": "_可选实验 B。_ 对同一条 trace 连打 {runs} 次，检验裁判可重复性",
        "exec.cleanup": "全部拆掉，包括 Customizer 附加栈（按依赖逆序；幂等）",
        "exec.again": "*（再跑一次）*",
        "exec.required_time": "~5 分钟",
        "timing_footnote": (
            "\\* 耗时沿用模板在 3 个问题下的实测值。本场景要问 {total} 个 practice 问题，每个都由 Mind the Goal 评判并跑 L1 检查"
            "（span 轮询最多 {l1_wait} 秒），所以 09、10、12 会更久。"
        ),
        "scenario_note": "> **场景说明：** {text}",
        "h.legend": ("打印的标签", "指标", "它回答什么问题", "分数低说明"),
        "legend": (
            ("Groundedness（有据性）", "每句话都有检索来源支撑吗？≥ {gr} 为通过。", "回答里有来源之外的内容（幻觉或自带常识）"),
            ("Source Precision（chunk 级）", "检索回来的整块 chunk 相关吗？", "检索拿回了跑题的 chunk"),
            ("Source Precision（fact 级）", "chunk 内部的事实里有多少真正相关？", "chunk 里大多是噪声；接近 0 说明检索失败"),
            ("Source Query Coverage（来源覆盖率）", "来源能覆盖这个问题吗？", "答案不在检索到的内容里"),
            ("Response Precision（回答精确率）", "回答是否切题？", "回答里堆砌了无关内容"),
            ("Response Query Coverage（回答覆盖率）", "问题是否被完整回答？", "问题有部分没答"),
            ("Self-Distinctness（自洽不重复）", "回答内部有没有重复？", "回答在重复自己"),
        ),
        "h.diagnosis": ("打印的模式", "含义", "该修的环节"),
        "diagnosis": (
            "回答冗长，信息相关但重复，可读性差",
            "检索不准，或源语料里缺少信息",
            "问题的各部分都覆盖到了，但部分检索来源只是勉强相关",
            "回答所需的信息在来源里有，但回答没用上",
            "回答夹带多余信息，但大部分检索来源是必要的",
            "生成器回答了来源没覆盖的内容，导致无据",
        ),
        "diagnosis.extra": (
            ("SP1 高 · SP2 低", "chunk 看着切题，但里面大部分事实是噪声", "源文档（清理知识库）"),
            ("SP2 ≈ 0", "检索失败：相关事实根本没被检索到", "检索——改提示词没用"),
        ),
        "diagnosis.levels": "LOW < {low}，HIGH ≥ {high}。`诊断: 无` 表示没有匹配的模式。",
        "h.rcof": ("代码", "失败根因"),
        "mtg.reading": (
            "`value` = GSR ÷ 100；GSR ≥ {gsr}% 的 session 为通过。`失败归因: E2:1` 按 RCOF 代码统计失败目标数；"
            "`无失败` 表示没有失败。"
        ),
        "h.l1": ("状态", "含义"),
        "l1.statuses": (
            ("PASS", "该问题声明的每项检查都通过"),
            ("FAIL", "有检查失败：detail 列写明是哪项（如 `mustMention fail: …`）"),
            ("DEFER", "L1 判不了（没有标记的拒绝或转交、否定语境里的禁用词）；交给 Mind the Goal 判定"),
            ("UNVERIFIED", "证据还没到位（没找到回答、工具 span 尚未索引）"),
            ("ERROR", "调用本身失败"),
        ),
        "l1.compare": (
            "在 10 里，表格末尾会有 `Against baseline-<epoch>:` 以及 `fixed`、`regressed`、`still-failing` 三类翻转；"
            "两次运行 SP2≈0 的 still-failing 问题会标注 `fix retrieval / the knowledge base, not the prompt`。"
        ),
        "h.messages": ("提示", "含义"),
        "messages": (
            ("`(spans not indexed yet, retry in {pause}s n/{attempts})`", "评估器还看不到这条 trace；脚本会自动重试"),
            ("`(span evidence incomplete, retry in {pause}s n/{attempts})`", "评估器跑了但看到的 trace 不完整；脚本会自动重试"),
            ("`已索引含检索 trace: x/y`", "索引等待：期望的 y 条检索 trace 已就绪 x 条"),
            ("`超时（仅 x/y 条就绪）`", "等待超时：某个本该检索的问题没有调用检索工具（看上面它的回答）"),
            ("`ERROR: evaluator did not return a usable score` / `ERROR: no usable evaluation scores`", "裁判没给出可用分数；脚本以 1 退出——重跑即可"),
        ),
        "look.noise": "检索到 {docs} 的 trace：SP1 高但 SP2 低——chunk 看着切题，却夹带跑题内容。",
        "look.gap": "{labels}：SP2 ≈ 0 或 SQC 低——检索没找到答案。",
        "look.fixable": "{labels}：来源覆盖了问题（SQC ≥ {sqc}），但 GR 低于 {gr}——基线提示词放任模型超出来源发挥。",
        "h.expect": ("时刻", "问题", "你应该看到", "为什么"),
        "expect.memory.where": "第 8 步（`06`）",
        "expect.memory": "一个通用的回答，然后是提示 `{notice}`——Agent 还不了解这个用户。第 10 步用同一身份再问一次。",
        "expect.prompt_fixable": "09：尽管来源覆盖了问题（SQC ≥ {sqc}），GR 仍低于 {gr}（Fail）。10 之后：GR 提升超过 max(裁判噪声带, {bar})——改提示词奏效。",
        "expect.retrieval_gap.buried": "09 和 10：检索失败（SP2 ≤ {sp2} 或 SQC < {sqc}），10 之后回答**仍然 Fail**——改提示词修不了，该修检索 / 知识库。",
        "expect.retrieval_gap.buried.advisory": "09 和 10：检索常常失败（SP2 ≤ {sp2} 或 SQC < {sqc}），但 Agent 换关键词再检索可能找到被埋没的答案，10 之后也可能 Pass。仅供参考：课堂对比以知识库里没有答案的缺口为准。",
        "expect.retrieval_gap.absent": "09 和 10：**检索什么也找不到**（SP2 ≤ {sp2} 或 SQC < {sqc}）。10 之后**优化后的 Agent 承认没有并转交处理**（L1 检查转交）；GR 甚至可能通过——提示词修好的是诚实，不是覆盖面。",
        "expect.tool_use.control": "L1 `requiredTools` / `forbiddenTools` 通过：答案来自 Gateway 工具，而不是知识库。",
        "expect.tool_use.contrast": "09：L1 工具检查失败。10 之后：通过——答案来自 Gateway 工具。",
        "expect.refusal.control": "Agent 拒绝（L1 `shouldRefuse` 通过；Mind the Goal 把场景要求的拒绝记为成功）。",
        "expect.refusal.contrast": "09：基线没有拒绝（L1 失败）。10 之后：拒绝了（L1 `shouldRefuse` 通过）。",
        "expect.escalation.control": "Agent 转交给正确的团队（L1 `shouldEscalate` 通过）。",
        "expect.escalation.contrast": "09：基线没有转交（L1 失败）。10 之后：转交了（L1 `shouldEscalate` 通过）。",
        "expect.noise_grounding": "检索到这些文档的 trace 会出现 SP1 高但 SP2 低（带噪声的 chunk）。仅供参考：它不决定对比结论。",
        "expect.documents": "文档：{titles}",
        "expect.noise_band": (
            "裁判噪声带是 THELMA 在两次相同运行之间自己波动的幅度；讲师用 `13-judge-stability.sh` 测量。"
            "小于 max(裁判噪声带, {bar}) 的变化不算提升。"
        ),
        "contrast.intro": "和优化前的分数对比（09 和 10 的 L1 表列出了每个 practice 问题）：",
        "contrast.fixable": "检索本来就好的问题（{labels}），有据性/精确率会提升——改提示词奏效；",
        "contrast.buried": "{labels}（SP2≈0，检索失败）**仍然 Fail**——改提示词修不了它；",
        "contrast.buried.advisory": "{labels}（答案被埋没）：检索常常失败（SP2≈0），但 Agent 换关键词再检索可能找到答案，10 之后也可能 Pass——仅供参考，下一条才是可靠的对比；",
        "contrast.absent": "{labels}：**检索什么也找不到**，优化后的 Agent **承认没有并转交处理**，而不是编一个答案——提示词修好的是诚实，不是覆盖面。",
        "contrast.close": "这个对比**印证了 THELMA 的诊断**：它能区分「该修提示词」还是「该修检索」。",
        "contrast.undeclared": (
            "和优化前的分数对比：检索本来就好的问题，有据性/精确率会提升；检索本身失败（SP2≈0）的问题仍然 Fail——改提示词修不了它。"
        ),
        "adlc.tip": "在本场景中：改提示词应当提升 {fixable} 的有据性，但修不了 {gaps}：{why}。",
        "adlc.tip.buried": "它们的检索失败了（SP2≈0）",
        "adlc.tip.absent": "知识库里没有答案，优化后的 Agent 必须承认并转交",
        "adlc.tip.mixed": "它们的检索失败，或知识库里根本没有答案",
        "adlc.undeclared": (
            "最有说服力的是这个对比：改提示词能在「检索本来就好」的地方提升有据性，但**修不了**一个检索本身就失败（`SP2≈0`）的问题。"
        ),
        "join.and": " 和 ",
        "join.list": "、",
        "attr.kb": "知识库包含为本场景编写的 {docs} 份文档（{doc_tags}）；其中 {noise} 份带有刻意的教学噪声，好让 THELMA 暴露检索质量问题。",
        "attr.customer": "客户材料经客户批准使用。",
        "generated_by": "_由 Workshop Customizer {version} 为场景包 `{pack}` 生成，模板提交 `{commit}`。_",
        "supplement.heading": "场景补充说明",
        "h.meta": ("字段", "值"),
        "meta.pack": "场景包",
        "meta.kind": "场景包类型",
        "meta.language": "语言",
        "meta.template": "模板提交",
        "meta.generator": "生成器版本",
        "meta.scenario": "场景文件 sha256",
        "h.matrix": ("条目", "customer_confirmed", "sa_synthetic", "ai_draft", "pending"),
        "matrix.facts": "事实",
        "matrix.tools": "工具",
        "matrix.documents": "文档",
        "matrix.golden": "Golden 问题",
        "matrix.narrative": "Guide 叙述",
        "waived": "已豁免的门禁项：{items}",
        "h.anchors": ("类别", "依据全部已确认的已确认 golden 问题", "状态"),
        "anchor.ok": "OK",
        "anchor.missing": "缺失",
        "anchors.note": "仅供参考：面向课堂的客户场景需要每个类别至少一个客户确认的锚点问题；参考包按设计全部为合成内容。",
        "classification.line": "数据分级：{value}。",
        "customer.line": "客户：{name}；材料使用批准：{approval}。",
        "classification.unset": "未声明（合成的参考材料）",
        "h.declarations": ("声明", "值"),
        "decl.first": "第一次对话（06）",
        "decl.probes": "检索 probe P（09 want = N = RECENT_N）",
        "decl.fixable": "改提示词可修",
        "decl.gaps": "检索缺口",
        "decl.stability": "稳定性问题（最后问；13 重复评它）",
        "decl.order": "评估顺序（09 / 10 / 12）",
        "decl.declared": "已声明",
        "decl.undeclared": "未声明——课堂上无法可靠地演示对比",
        "warnings.none": "没有校验器警告。",
        "checklist": (
            "你要教的 release（`{version}`）上 15 个 Guided Run 步骤全部通过，报告状态为 complete。",
            "基线有 {n} 个可用的 THELMA 分数（每个检索 probe 一个）。",
            "改提示词可修的 probe（{fixable}）：GR 提升 > max(裁判噪声带, {bar})，且 sampleCountsMatch = true。",
            "检索缺口（{gaps}）：两次运行都 SP2 ≤ {sp2} 或 SQC < {sqc}；{gap_outcome}。",
            "工具调用、拒绝和转交问题在 10 之后通过各自的 L1 重点检查。",
            "已记录裁判稳定性（13）并应用裁判噪声带（≤ {band_max}）。",
            "`run/rehearsal.json` 显示本 release 可以上课（ready for class）。",
            "只有客户确认的事实（表 2.1）被当作该组织的规则讲授。",
        ),
        "gap_outcome.buried": "被埋没的缺口在 10 之后仍然 Fail",
        "gap_outcome.absent": "对知识库里没有答案的缺口，优化后的回答承认没有并转交",
        "gap_outcome.mixed": "对知识库里没有答案的缺口，优化后的回答承认没有并转交；被埋没的缺口（{buried}）仅供参考：换关键词再检索可能找到答案、10 之后被判 Pass",
        "h.runsheet": ("Guide 步骤", "脚本", "Guided Run", "约耗时", "学员应该看到", "讲师提示"),
        "run.not_guided": "不在 Guided Run 中",
        "run.separate": "单独的破坏性流程",
        "h.truth_facts": ("Id", "陈述", "重要性", "确认人", "依据 / 来源", "类别（来源类型）"),
        "h.truth_docs": ("Id", "标题", "文件", "来源", "教学噪声", "教学作用"),
        "h.truth_tools": ("工具", "类型", "来源", "行为"),
        "tool.default": "默认",
        "tool.when": "当",
        "tool.error": "错误",
        "doc.role.noise": "noise_grounding",
        "doc.role.bait": "诱饵",
        "doc.role.answer": "{cases} 的答案",
        "h.answer": ("字段", "值"),
        "answer.question": "问题",
        "answer.asked": "提问身份",
        "answer.expected": "期望",
        "answer.basis": "依据",
        "answer.roles": "教学作用",
        "answer.evaluated": "评估方",
        "answer.persona": "身份 `{persona}`（运行时的新 actor `{persona}-<RUN_TAG>-q{index}`），角色 `{role}`",
        "answer.declared_actor": "声明的 actor `{actor}`，角色 `{role}`",
        "answer.holdout_eval": "不执行（留出集）",
        "answer.stability": "稳定性问题",
        "answer.probe": "检索 probe",
        "holdout.use": (
            "本 release 的任何脚本都不会执行留出集问题，App 也没有调用它们的路由（信任模型只允许两个固定的 SSM 文档）。"
            "课堂运行结束后把它们用于讨论：在 Workshop 环境里手动问一个（在 `~/workshop/{agent}` 下运行 `npx agentcore invoke`），"
            "再把回答和上面的期望值对比。学员能看到屏幕时，绝不要把它们贴到幻灯片或聊天里。"
        ),
        "rehearsal.none": (
            "本次构建还没有记录彩排证据。在这个 release 上跑完 Guided Run 之后，App 会在这里（讲师 Guide 视图）显示彩排结论，"
            "并在讲师包里加入 `rehearsal-evidence.md`。"
        ),
        "fallback.generic": (
            "课堂备选方案：如果本场景彩排未就绪，或课上运行出了问题，就改讲通用 Workshop（`hr-default`，与上游兼容的参考"
            "场景包）——但只能在为它准备好的环境里讲。附加栈只为一个场景包的命名空间授予 Workshop EC2 权限，所以 hr-default "
            "无法在本场景的环境里运行，回滚也只替换 release 文件。请另备一个已同步并彩排过 hr-default 的环境（它自己的彩排"
            "必须显示可以上课），或者在课前运行 `./99-cleanup.sh --scenario-only`，用 "
            "`tools/deploy_addons.py --scenario scenarios/hr-default/scenario.yaml` 重新部署附加栈（之后本场景在该环境里"
            "不再能运行），再同步 hr-default 并彩排。"
        ),
        "rehearsal.bundle_title": "彩排证据——{version}",
        "rehearsal.verdict": "结论：**{verdict}**",
        "rehearsal.ready": "可以上课：**{ready}**",
        "rehearsal.release": "Release：`{release}`",
        "rehearsal.generated": "生成时间：{at}",
        "rehearsal.reason": "原因：{reason}",
        "rehearsal.blockers": "就绪阻塞项：{blockers}",
        "rehearsal.report_complete": "Guided Run 报告完整：**{value}**",
        "rehearsal.guides_built": "两份 Guide 均已生成：**{value}**",
        "rehearsal.noise_band": "裁判噪声带：{value}",
        "rehearsal.noise_source": "来源 {source}",
        "rehearsal.noise_verdict": "稳定性结论 {verdict}",
        "rehearsal.missing": "缺失的证据：{items}",
        "rehearsal.stale": "这份证据属于 release `{release}`，不是本 Guide 对应的 release；上课前请重新彩排。",
        "h.rehearsal": ("教学现象", "类型", "结论", "证据"),
        "rehearsal.remediation": "修复提示：",
        "rehearsal.empty": "彩排记录里没有任何教学现象。",
        "rehearsal.blocker": "{code}（{text}）",
        "rehearsal.evidence_sep": "；",
        "rehearsal.case": "{case}：{code}",
        "rehearsal.case_reason": "{case}：{code}——{reason}",
        "rehearsal.warnings": "提醒：",
        "rehearsal.warning_refs": "{refs}：{text}",
        "rehearsal.code_reason": "{code}——{reason}",
        "rehearsal.list_sep": "、",
        "rehearsal.noise_details": "{value}（{details}）",
        "rehearsal.hint": "{action}原因：{because}",
        "rehearsal.sentence_end": "。",
        "rehearsal.hint_where": "{where}：{text}",
        "rehearsal.hint_tagged": "**{severity}** {text}",
        "rehearsal.severity.blocking": "阻断",
        "rehearsal.severity.advisory": "建议",
        "report.fields": (
            ("`report.teachingContrast.currentRun`", "本次运行的 reproduced / not_reproduced / insufficient_evidence；每个教学现象列出逐题代码"),
            ("`quality.delta.<evaluator>`", "基线与优化后的均值；只有 sampleCountsMatch = true 且 |delta| > 裁判噪声带时才算变化"),
            ("`quality.regressions`", "均值下降超过裁判噪声带的评估器"),
            ("`quality.comparisonWarnings`", "可用分数的个数不同：均值差只作描述"),
            ("`completion.missingEvidence`", "某一步没有交付的证据（逐题 L1、逐题 Mind the Goal、裁判噪声带）"),
            ("`scopeWarning`", "报告验证的是 Workshop 运行，不是生产上线"),
            ("`run/rehearsal.json` `readyForClass`", "唯一的上课就绪判定（结论 ready ∧ 报告 complete ∧ 两份 Guide 都已生成）"),
        ),
        "h.report": ("报告字段", "怎么读"),
        "h.facilitation": ("报告里的代码", "发生了什么", "课堂上怎么说", "课后怎么做"),
        "facilitation": (
            ("PF_BASELINE_ALREADY_PASSES", "基线在这个 probe 上已经有据（GR ≥ {gr}）。", "今天提示词的缺陷没在这个问题上显现；展示一个确实提升了的 probe。", "加强基线缺陷或答案附近的噪声，重新构建并再次彩排。"),
            ("PF_NO_GAIN", "GR 变化小于 max(裁判噪声带, {bar})。", "LLM 裁判会波动；看趋势和诊断，别盯一个数。", "彩排时重跑一次 09/10；如果重复出现，重新审视候选提示词。"),
            ("PF_RETRIEVAL_FAILED", "来源没有覆盖问题（最大 SQC < {sqc}）。", "这是检索问题而不是提示词问题——和缺口同一个道理。", "检查答案文档和分块；重新构建。"),
            ("RG_RETRIEVAL_OK_BASELINE / RG_RETRIEVAL_OK_OPTIMIZED", "检索找到了缺口问题的答案（SP2 > {sp2} 且 SQC ≥ {sqc_gap}）。", "今天检索碰巧成功了；讲解 SP2≈0 本该呈现什么。", "从知识库删掉答案（absent）或把它埋得更深（buried）；重新构建。"),
            ("RG_OPTIMIZED_RESOLVED", "被埋没的缺口在 10 之后被判 Pass。", "指出 SP2：检索仍然失败。看优化后的回答：如果它写出了那条规定，是换关键词再检索（或模型自己的知识）补上的；如果它说没找到并转交，是裁判给一个有据的「没有答案」判了 Pass。", "把这一课讲在「知识库里根本没有答案」的那道题上；埋没式缺口不可靠（包里没有 absent 缺口就加一个）。"),
            ("JUDGE_TOO_NOISY / NOISE_BAND_MISSING", "裁判噪声带高于 {band_max} 或从未测量。", "今天不要根据 THELMA 的数值宣称有提升。", "跑 13，校准 evaluation.noiseBand，重新构建。"),
            ("L1_UNRESOLVED / L1_MISSING", "L1 交给了 Mind the Goal 但它没给结论，或者 L1 没跑。", "把回答念出来，对照学员 Guide 第 1 节的场景规则判断。", "补充转交或拒绝标记（evaluation.l1），让 L1 能判；重新构建。"),
            ("L1_OPTIMIZED_FAILS", "优化后的 Agent 没通过工具、拒绝或转交检查。", "这是回退：该不该上线由评估器决定，而不是直觉。", "修改候选提示词或问题期望；重新构建。"),
        ),
        "h.troubleshoot": ("现象", "处理"),
        "troubleshooting": (
            ("`Stack 'workshop-infra' has no DataBucketName/SkillsBucketName output`", "先跑第 2 步（`00-deploy-infra.sh`）。"),
            ("`Gateway ARN not found in SSM`", "跑第 4 步（`02-create-gateway.sh`）。"),
            ("`04-deploy.sh` 找不到 `SkillsFilesAccessPointArn`", "缺少 `workshop-customizer-addons` 栈：环境没有准备好；从 App 部署它。"),
            ("`05-setup-memory.sh`：requested release is not active", "从 App 应用（sync）本 release，让 `~/workshop/current` 指向它。"),
            ("`Model access is denied` / `aws-marketplace:Subscribe`", "开通模型访问，或把 `00-config.sh` 里的 `WORKSHOP_MODEL_ID` 改成账号可用的模型。"),
            ("找不到 `uv`（08 无法打包评估器）", "`export PATH=\"$HOME/.local/bin:$PATH\"`（第 9 步）。"),
            ("09 重试或 `no usable evaluation scores`", "重跑同一条命令；裁判或 span 索引滞后了。"),
            ("09 索引等待超时", "某个本该检索的问题没有检索；看它的回答和 L1 表。"),
            ("`Set verified PRICE_IN and PRICE_OUT`", "为该模型和区域导出 `PRICE_IN` / `PRICE_OUT`（每 1M token 的美元价）。"),
            ("`Model produced invalid sequence as part of ToolUse`", "对比模型（如 Nova Micro）跑不了这个 Agent 拓扑；换一个模型。"),
            ("09：某道题的基线回答以 `Model stopped generating due to maximum token limit` 结尾", "回答写到了 8192 token 的 `--max-tokens` 上限。这一行之前的部分回答照样打分（THELMA、Mind the Goal；L1 检查的是截断后的回答，所以 mustMention 不通过可能是被截掉了）。基线要求补充额外建议时，基线轮偶尔出现一次属正常；多道题出现、或优化轮也出现，就检查提示词里对篇幅的要求。"),
            ("13 打印 `数据不足`", "可用分数少于两个；等 trace 索引后重跑。"),
            ("99 以 75 退出（`Cleanup pending`）", "AgentCore ENI 最长可能要 8 小时才释放；稍后重跑同一条命令。"),
        ),
        "experiments.fix": (
            "修检索（仅供讨论；它需要重新构建 release，绝不在课堂上改）：清理带噪声的文档、把被埋没缺口的答案段落拆出来，"
            "或为知识库里没有答案的缺口补上缺失的内容；重新构建并再次彩排——缺口问题应当能从知识库得到回答。"
        ),
        "observations.none": "没有实验观察记录。",
        "supplement.none": "没有讲师补充说明。",
        "design_rationale": "设计说明：",
        "prompt.diff": "基线 → 优化候选（`pack/prompts/baseline.md` → `pack/prompts/optimization-candidate.md`）：",
        "defects.intro": "候选提示词修复的基线缺陷：",
        "h.defects": ("缺陷", "基线缺少什么", "候选提示词的修复"),
        "memory.check": "参考性的 Memory 检查：06 的回答不应提到 {terms}（用户本人的数据）。",
        "gap.terms": "缺失词（知识库里不能有）：{terms}。诱饵词（在噪声文档里）：{bait}。",
        "gap.bait": "诱饵词（在噪声文档里）：{bait}。",
        "gap.docs": "文档：答案 {answer}；诱饵 {bait}。",
        "l1.kind_note": "设计：{design}。重点检查：{checks}。",
        "noise.lead": "为了让评估有意义，知识库被**故意灌入了教学噪声**——这样 THELMA 的分数才能暴露真实的检索质量问题，而不是给出一个干净的玩具级结果：",
        "noise.none": "本场景的知识库没有刻意的教学噪声。",
        "noise.docs": "其中 {n} 份文档带有刻意的教学噪声（跑题段落），所以检索质量问题会在 THELMA 里显现。",
        "experiments.heading": "场景实验",
        "run.see.setup": "账号 ID 和区域；创建了 Skill 目录",
        "run.see.infra": "`workshop-infra` 的输出（栈已存在）",
        "run.see.knowledge-base": "知识库 `{kb}` 的详情；{docs} 份文档已入库",
        "run.see.gateway": "Lambda `{fn}` 和 Gateway `{gw}`；ARN 已写入 SSM",
        "run.see.skills": "上传了 {skills} 个 SKILL.md 文件",
        "run.see.agent": "Harness `{agent}` 以 VPC 模式部署完成",
        "run.see.memory": "Runtime READY；Memory 检索已配置",
        "run.see.conversation": "问题提示行、一个通用回答、Memory 提示",
        "run.see.eval-env": "`uv` 已安装；Transaction Search 已开启",
        "run.see.conversation-rerun": "以 `{actor}` 再问同一个问题",
        "run.see.evaluators": "`{thelma}` 和 `{mtg}` 已注册；打印出裁判模型",
        "run.see.baseline": "{total} 个问题、{n} 条检索 trace 被打分、每个问题的 Mind the Goal、L1 表",
        "run.see.optimize": "重问同样的 {total} 个问题；相对基线的 L1 翻转；结尾的解读",
        "run.see.cost-latency": "{recent} 条 trace 的延迟、token 和成本",
        "run.see.models": "对比分数；基线模型已还原",
        "run.see.judge-stability": "一条 trace 的 {runs} 个分数、均值 / 标准差 / 极差和结论",
        "run.see.cleanup": "资源已删除，或 `Cleanup pending` 并以状态 75 退出",
        "run.note.setup": "",
        "run.note.infra": "准备好的环境里栈已存在；脚本只打印它的输出。",
        "run.note.knowledge-base": "入库前会删除知识库前缀下之前场景包的对象。",
        "run.note.gateway": "",
        "run.note.skills": "",
        "run.note.agent": "需要 `workshop-customizer-addons` 栈（`SkillsFilesAccessPointArn`）。",
        "run.note.memory": "需要本 release 是主机上当前生效的 release；Guided Run 拒绝其他 release。",
        "run.note.conversation": "Guided Run 只在 07 之前跑一次 06；Guide 第 10 步只由学员执行。",
        "run.note.eval-env": "",
        "run.note.conversation-rerun": "仅学员执行：Transaction Search 只捕获第 9 步之后产生的 span。",
        "run.note.evaluators": "Mind the Goal 按场景规则（范围、转交、禁止行为）评判。",
        "run.note.baseline": "只有在 guided runner 下（`WORKSHOP_NONINTERACTIVE=1`），Mind the Goal 的失败才是致命的。",
        "run.note.optimize": "把结尾的解读和第 3.2 节对照。",
        "run.note.cost-latency": "",
        "run.note.models": "guided 模式下的 12 不交互，并使用 target 配置的对比模型。",
        "run.note.judge-stability": "上课前把抖动换算成 `evaluation.noiseBand`（App：calibrate）。",
        "run.note.cleanup": "从不自动运行，也不属于 Guided Run。`--scenario-only` 保留 `workshop-infra` 和附加栈（课前重新同步改过的 pack）。",
    },
}


def lang_key(language: str | None) -> str:
    """The guide language of a pack: ``zh-CN`` packs get the Chinese templates, every other pack English."""
    return "zh-CN" if language == "zh-CN" else "en"


def text(lang: str, key: str) -> object:
    """``STRINGS[lang][key]`` (KeyError for an unknown key: a template or engine bug)."""
    return STRINGS[lang_key(lang)][key]
