# FAQ pairs derived from the HR-MultiWOZ dataset (Apache-2.0), arXiv:2402.01018
DOMAIN_FAQS = {
    'access_request': [
        ('What is the main topic or subject of the training you are requesting?', 'machine learning'),
        ('What is the purpose of this access request?', 'required for my job responsibilities'),
        ('Are there any additional notes or comments related to this access request?', 'No, there are no additional notes needed'),
        ('How long do you need the access for? (Specify duration in days, weeks, or months)', 'ongoing basis'),
        ('Please provide your contact information (Name, Email, Phone).', 'Amir Khaled'),
        ('What type of access are you requesting? (e.g., System, Building, Document)', 'system access'),
        ('Do you have approval from your supervisor or a relevant authority? (Name of approver)', 'John Smith'),
        ('Have you had access to these resources or areas before? (Please describe)', 'Yes, I had access approximately 3 years ago'),
        ('Are there specific resources or areas you need access to? (Please specify)', 'accounting software system'),
        ('Please provide your employee or user identification number.', 'AK230981'),
    ],
    'benefits_enrollment': [
        ('Please enter your preferred contact method (Email, Phone, Mail).', 'social media'),
        ('Do we have your updated personal information on file? (Answer with Yes or No)', 'Yes'),
    ],
    'general': [
        ('What is the main topic or subject of the training you are requesting?', 'photography skills'),
        ('Are there specific resources or areas you need access to? (Please specify)', 'just the systems in general'),
        ('What type of access are you requesting? (e.g., System, Building, Document)', 'systems in general'),
    ],
    'goal_setting': [
        ('What are the desired outcomes or goals of this training?', 'better research skills'),
        ('What type of additional training, if any, does the employee need?', 'pastry skills'),
        ('What goals should be set for the next review period?', 'Learning new cuisines'),
        ('Describe the skill development or learning growth shown by the employee.', "I've learned some new programming languages"),
        ('What is the name of the employee being reviewed?', 'Henry Kim'),
        ('How well did the employee achieve their set goals? (Rate from 1 to 5)', 'most'),
        ('By when do you aim to achieve this goal? (Enter the date in YYYY-MM-DD format)', 'December 31st, 2040'),
        ('What measurable criteria will you use to determine if the goal has been achieved?', 'Reaching my target savings amount'),
        ('What motivates you to achieve this goal?', 'I want to have a comfortable retirement'),
        ('What is the specific goal you want to achieve?', 'save enough money for a comfortable retirement'),
    ],
    'harassment_report': [
        ('Are there any additional notes or observations you would like to report?', 'no additional notes'),
        ('What type of safety incident are you reporting? (e.g., Workplace Injury, Fire, Hazardous Material Spill)', 'workplace injury'),
        ('What time did the harassment occur? (Enter the time in HH:MM format)', '9:30 this morning'),
        ('What type of harassment are you reporting? (e.g., Workplace, Online, Physical, Verbal)', 'verbal'),
        ('Where did the harassment occur? (Please specify the location)', 'the office kitchen'),
        ('What outcome or resolution are you seeking with this report?', 'An apology from my manager and some workplace training'),
        ('Please describe the harassment incident in detail.', 'My manager yelled insults at me'),
        ('When did the harassment incident occur? (Enter the date in YYYY-MM-DD format)', 'May 15th, 2020'),
        ('How has this incident affected you or the victim?', "I've been feeling quite upset and embarrassed"),
        ('How severe is the incident? (e.g., Minor, Moderate, Severe)', 'moderate'),
    ],
    'it_issue_report': [
        ('How many people will be participating in the training? (Enter a number)', 'Three'),
        ('How long should the training last? (Specify in hours or days)', 'two days'),
        ('What is your budget for this training? (Enter the amount in your local currency)', '$5000'),
        ('What are the desired outcomes or goals of this training?', 'better research skills'),
        ('What type of additional training, if any, does the employee need?', 'pastry skills'),
        ('Describe any leadership qualities exhibited by the employee.', 'I mentor junior chefs'),
        ('What is the purpose of this access request?', 'required for my job responsibilities'),
        ('Are there any additional notes or comments related to this access request?', 'No, there are no additional notes needed'),
        ('What type of access are you requesting? (e.g., System, Building, Document)', 'system access'),
        ('Do you have approval from your supervisor or a relevant authority? (Name of approver)', 'John Smith'),
    ],
    'performance_review': [
        ('What is the time period for this review? (Enter the date range in YYYY-MM-DD format)', 'the past year'),
        ('What is the name of the employee being reviewed?', 'Amir Khaled'),
        ('What goals should be set for the next review period?', 'Learning new cuisines'),
        ('What type of additional training, if any, does the employee need?', 'any additional training is needed'),
        ('What areas require improvement for the employee?', 'time management skills'),
        ('Describe the skill development or learning growth shown by the employee.', "I've learned some new programming languages"),
        ('What is the overall performance rating of the employee? (Rate from 1 to 5)', 'exceeded expectations'),
        ('How will you track and measure your progress?', 'review my account balances'),
        ('How do you plan to hold yourself accountable to this goal?', "I'll review my progress with my spouse every few months"),
        ('How often do you plan to review and assess your progress? (e.g., Weekly, Monthly)', 'Every three months'),
    ],
    'relocation_request': [
        ('What is the main topic or subject of the training you are requesting?', 'machine learning'),
        ('What is the purpose of this access request?', 'required for my job responsibilities'),
        ('Are there any additional notes or comments related to this access request?', 'No, there are no additional notes needed'),
        ('What type of access are you requesting? (e.g., System, Building, Document)', 'system access'),
        ('Do you have approval from your supervisor or a relevant authority? (Name of approver)', 'John Smith'),
        ('Do you have any specific transportation needs for the relocation? (e.g., Vehicle transport, Flight arrangements)', "Yes, I'll need help arranging for my vehicle to be transported"),
        ('Are there any special accommodations or requirements needed for the relocation?', "No, I don't have any other special needs"),
        ('What is the primary reason for your relocation? (e.g., Job transfer, Family, Education)', 'job transfer'),
        ('Is this relocation temporary or permanent?', 'permanent'),
        ('When do you wish to relocate? (Enter the date in YYYY-MM-DD format)', 'by June 1st, 2023'),
    ],
    'safety_incident_report': [
        ('Are there any additional notes or observations you would like to report?', 'no additional notes'),
        ('What type of safety incident are you reporting? (e.g., Workplace Injury, Fire, Hazardous Material Spill)', 'workplace injury'),
        ('What immediate actions were taken following the incident?', 'First aid'),
        ('How many individuals were affected by the incident? (Enter a number)', 'one'),
        ('When did the incident occur? (Enter the date in YYYY-MM-DD format)', '2023-02-15'),
        ('Where did the incident occur? (Please provide the specific location)', 'in the office'),
        ('What time did the incident occur? (Enter the time in HH:MM format)', '10:00 AM'),
        ('How severe is the incident? (e.g., Minor, Moderate, Severe)', 'moderate'),
        ('Were there any witnesses to the incident? (Provide names or state "None")', 'no witnesses'),
        ('What time did the harassment occur? (Enter the time in HH:MM format)', '9:30 this morning'),
    ],
    'time_off_report': [
        ('What is the time period for this review? (Enter the date range in YYYY-MM-DD format)', 'the past year'),
        ('What areas require improvement for the employee?', 'time management'),
        ('What is the name of the employee being reviewed?', 'Amir Khaled'),
        ('Are there any additional notes or observations you would like to report?', 'no additional notes'),
        ('What type of safety incident are you reporting? (e.g., Workplace Injury, Fire, Hazardous Material Spill)', 'workplace injury'),
        ('Where did the incident occur? (Please provide the specific location)', 'in the office'),
        ('What time did the incident occur? (Enter the time in HH:MM format)', '10:00 AM'),
        ('What type of time off are you requesting? (e.g., Vacation, Sick Leave, Personal Day)', 'vacation'),
        ('Will you be available for contact during your time off? (e.g., Yes, No, Limited availability)', 'limited availability'),
        ('What is the reason for your time off? (Optional, but may be required for certain types of leave)', 'planned vacation'),
    ],
    'training_request': [
        ('What is the main topic or subject of the training you are requesting?', 'machine learning'),
        ('Are there any special requirements or accommodations needed for the training?', 'no special accommodations are needed'),
        ('How many people will be participating in the training? (Enter a number)', 'Three'),
        ('How long should the training last? (Specify in hours or days)', 'two days'),
        ('What is your budget for this training? (Enter the amount in your local currency)', '$5000'),
        ('What are the desired outcomes or goals of this training?', 'better research skills'),
        ('What are your preferred dates for the training? (Enter the dates in YYYY-MM-DD format)', 'June 15th, 2023'),
        ('What format do you prefer for the training? (e.g., Online, In-person, Workshop, Seminar)', 'online seminars'),
        ('Please provide contact information for the person coordinating the training (Name, Email, Phone).', 'hkim@researchlab.com or 555-1234'),
        ('What type of additional training, if any, does the employee need?', 'pastry skills'),
    ],
}
